#if !canImport(ObjectiveC)
import XCTest

extension RecursiveSyncDispatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecursiveSyncDispatchTests = [
        ("testBasicUsage", testBasicUsage),
        ("testSimpleUsage", testSimpleUsage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RecursiveSyncDispatchTests.__allTests__RecursiveSyncDispatchTests),
    ]
}
#endif
